### ISSUE TITLE
Display Default Page

### ISSUE THREAD

**Issue by martensonbj** [turingschool-projects/1608-remember-3#8]
Update reminder component to have a conditional that will only display notes if notes exist.

There should be a default welcome page welcoming users to the app and/or directions to create a new note. Feel free to be creative here.

**Comment by hilarylewis92** [comment]
Hi @martensonbj, 

We are a little confused by these instructions. Should we route every user to the default welcome page or should they only see that if there are no reminders? Right now, the model generates 5 random reminders on load from the mirage. I'm guessing we should get rid of that and only have real reminders?

Finally, by "notes", do you mean reminders or the "note" part of the reminder? 

Thanks

**Comment by martensonbj** [comment]
Yeah the wording of that first part isn't clear in retrospect. Basically we're just looking for a default page for a brand new user so if no reminders exist the user has an indication for what to do.

**Comment by martensonbj** [comment]
And notes = reminders.

**Comment by hilarylewis92** [comment]
Should our application route to the welcome page regardless of whether or not we have reminders on page load or should it route to reminders page if there are reminders saved on page load?
